### ISSUE TITLE
Code executed on jupyter kernel from h (hypothes.is)

### ISSUE THREAD

**Issue by jibe-b** [jupyter/kernel_gateway#105]
Hi there,

I am a user of both jupyter notebooks and [h](https://hypothes.is) and I think about the way the h sidebar + jupyter kernel could do a similar job to jupyter kernel + notebook.

Basically, code is written in the h sidebar, a ipynb file is sent to the kernel and executed, results and errors are sent to a temporary file that is watched by the h sidebar and displayed. Finally, if the user wants to store the code, it is stored in the h server as JSON.

A second step would be to enable the code to run remotely and to be sent to the h sidebar without a local temporary file.

This would enhance annotation/fact-checking with code and results, which is particularly useful in  discussion of scientific publications.

I have not yet looked at the kernel_gateway code. Do you think it enables what I try to do? Are there limitations somewhere?

**Comment by parente** [comment]
Thanks for opening this. I love to see ideas for new clients of Jupyter kernels!

I'm not familiar with h, but based on your description, I think the setup would be something more like the following:

1. User of h is on a site
2. User writes code in the h sidebar (e.g., in a fenced code block)
3. User selects the code and hits an execute button
4. When user executes the code for the first time, the h extension contacts a kernel gateway to request a kernel in the desired language (for simplicity, let's pretend the kernel gateway and kernel live somewhere in the cloud, say, as a service the h authors provide)
4. The h sidebar sends the code (not a notebook ipynb file) to the provisioned kernel / kernel gateway for evaluation following the [jupyter protocol](http://jupyter-client.readthedocs.org/en/latest/)
5. Kernel responds and h renders the result inline.
6. h saves the code in one of its annotations however it wants.

The key difference between your proposal and this is that the kernel gateway, when operating in its normal jupyter-websocket mode, doesn't know anything about ipynb files. It takes [jupyter protocol messages](http://jupyter-client.readthedocs.org/en/latest/) on a websocket, sends them to a jupyter kernel on 0mq (which is what all kernels talk), and does the reverse for messages that come from kernels.

The jupyter-js-services npm package provides a nice library for requesting kernels from a kernel gateway and sending them code. Here's an example:

https://github.com/jupyter-incubator/kernel_gateway_demos/blob/master/node_client_example/client.js

Since the kernel gateway uses HTTP and Websockets, you can use pretty much any language to communicate with it. Here's another example in Python which doesn't have a nice library like nodejs (yet?)

https://github.com/jupyter-incubator/kernel_gateway_demos/tree/master/python_client_example

**Comment by jibe-b** [comment]
Thanks for answering with details!

The process will likely be simple like this, and can be developed with a local h server. I only need to know more about the jupyter protocols to do it, and your description shows it is rather simple too.

I will try something in the next weeks (but don't expect it too quickly) and I may come back with further questions.

**Comment by parente** [comment]
@jibe-b I'm going to close this issue. If you did attempt the h experiment, feel free to let us know the outcome in new issues or in the Jupyter Google group.
