### ISSUE TITLE
How to connect to external/custom kernel?

### ISSUE THREAD

**Issue by teaglebuilt** [jupyter/kernel_gateway#331]
```
--KernelGatewayApp.default_kernel_name=RobotKernel....
```

RobotKernel is not on the list from Jupyterhub.  

https://github.com/robots-from-jupyter/robotkernel

How would i go about using the kernel with kernel_gateway?

**Comment by kevin-bates** [comment]
Setup of kernels for use by KernelGateway should be no different than for Notebook.  The primary difference is that the kernel is not necessarily local to the notebook server, so some steps need to be taken to address file access, etc.

Have you configured Hub to start notebook servers using the `--gateway-url` or are you using `NB2KG` to trigger Notebook kernel management to proxy to the Gateway server?

Not sure if your issue is general, independent of robotkernel, or specific to robotkernel.

**Comment by teaglebuilt** [comment]
im going through the kernel gateway demos. I believe I am using NB2kg, my question is not specific to robotkernel. Maybe any custom kernel or external from Jupyters ecosystem  that cannot be referenced in the dockerfile as Jupyter/kernel-type

**Comment by kevin-bates** [comment]
Yeah, setting up a gateway server (Kernel or Enterprise) can be a bit involved.  You might want to checkout [this blog post](https://blog.jupyter.org/on-demand-notebooks-with-jupyterhub-jupyter-enterprise-gateway-and-kubernetes-e8e423695cbf).  Its relative to Enterprise Gateway but should be just as applicable to Kernel Gateway.  

One big difference is that with Notebook 6.x, the NB2KG extension (and all its configuration steps) is no longer necessary.  You really just need to launch (or configure) Notebook with `--gateway-url=<URL to gateway server>` since NB2KG is essentially baked in to NB 6.x.

> ... referenced in the dockerfile as Jupyter/kernel-type

Could you elaborate on this?  How are kernels being referenced in the dockerfile at all?  Or are you referring the docker _image_ when you say dockerfile?  So long as kernels (custom or otherwise) are properly discoverable and can be launched via the framework, then you should be fine.  If you're attempting to use new custom kernels, I would recommend they first be tested in a standard Notebook environment before moving to Hub and containers.
