### ISSUE TITLE
Future of kernel gateway ?

### ISSUE THREAD

**Issue by btribonde** [jupyter/kernel_gateway#334]
I'm currently using jupyter-kernel-gateway as a dependencie for my project (https://github.com/CFMTech/Jupytab) but suffers from the lack of new release to fix bugs like #325 (merged, but no release since sept-19) or linked to new release of Tornado on windows using python 3.8 (https://github.com/tornadoweb/tornado/issues/2751).

I would be glad to contribute as I prefer to not internalize the kernel gateway code for the http_notebook_mode feature, but I need to know if I can still rely on future release of this project (I understand it is probably no more a priority with the enterprise gateway...)

**Comment by kevin-bates** [comment]
Hi @btribonde - thank you for opening this issue.  You're absolutely right that kernel gateway has been neglected from a maintenance perspective and a more dedicated volunteer would be welcome.  Would you be interested in a maintainer role?

While it's true the Enterprise Gateway replaces (and extends) much of the functionality of JKG, there are definitely use-cases covered by JKG, especially since EG no longer depends on JKG (to provide things like HTTP personality).  JKG is perfectly valid if you'd like to detach your notebook files from the server but still just want kernels local to the launching server, or if the HTTP personality is desired.

I will try to put together a 2.4.1 release in the next day or two.

**Comment by btribonde** [comment]
Hi @kevin-bates 
Thanks for your quick reply and future release. I will not have a lot of time to work on this as I have already other projects (like jupytab) but at least I may contribute to fix bugs and extending tests on windows or other platforms.

**Comment by kevin-bates** [comment]
Ok - that sounds great!  I think this repository will just require "pings" (like this issue) from time to time since there really isn't a fulltime maintainer.  Your patience is appreciated.

Btw, are you suggesting a dependency change be made relative to this comment?
> or linked to new release of Tornado on windows using python 3.8 (tornadoweb/tornado#2751)

If so, would you mind providing a pull request?

**Comment by btribonde** [comment]
Of course, I have met this issue but don't know if it is linked to jupytab or kernel-gateway. But as we use the same version of tornado probably both.
I will solve this in both repository no problem.

**Comment by kevin-bates** [comment]
FYI - I've gone ahead and published 2.4.1: https://pypi.org/project/jupyter-kernel-gateway/

**Comment by btribonde** [comment]
Thanks a lot !

**Comment by kevin-bates** [comment]
Right on.  I'm going ahead and closing this issue.  Please feel free to ping us from time to time here. :smile:
