### ISSUE TITLE
Can't access environment variables with remote kernel

### ISSUE THREAD

**Issue by sa-** [jupyter/kernel_gateway#361]
```
import os
print(os.environ['HOME'])
print(os.environ['SPARK_HOME'])
# empty strings are printed
```

These variables are present when I echo them though ssh

I have 2 env vars that I would like to access, but it seems that kernelgateway doesn't let us access them. Is this by design? Are there any workarounds/fixes?

**Comment by kevin-bates** [comment]
Hi @sa-.  This is by design in order to prevent kernel instances from inheriting env values that might be considered sensitive.  Take a look at the configuration option [`--KernelGatewayApp.env_process_whitelist`](https://jupyter-kernel-gateway.readthedocs.io/en/latest/config-options.html#configuration-options). This is a list-valued property consisting of environment variable names that can be inherited by the spawned kernel.   Here's an example:

```
$ export FOO=fff
$ export BAR=bbb
$ jupyter-kernelgateway --KernelGatewayApp.env_process_whitelist="['BAR','FOO']"
```
and from the kernel...
![image](https://user-images.githubusercontent.com/22599560/117555745-a4778f00-b016-11eb-935d-655038166407.png)

This option can also be set via an env (which I find a bit easier): 
```
$ export KG_ENV_PROCESS_WHITELIST=FOO,BAR
$ jupyter-kernelgateway
```

**Comment by gdagil** [comment]
Thank you for your decision, but this does not have the best effect on running remote kernels in docker containers, please, could you add a `bool` type parameter in order for variables to be thrown through, and I should not have reinvented the wheel like this

```bash
export ENV_WHITELIST=$(env | cut -d= -f1 | awk '{printf "\"%s\",", $0}' | sed 's/,$//')
echo "[$ENV_WHITELIST]"

jupyter kernelgateway \
            --port=8881 \
            --ip=0.0.0.0 \
            --JupyterWebsocketPersonality.env_whitelist="[$ENV_WHITELIST]"
```

**Comment by kevin-bates** [comment]
Hi @gdagil - I see that you're setting `ENV_WHITELIST`, implying that you'd essentially like to allow any environment variables that are specified in the kernel's start request body AND specified in your JKG process's env to pass through.  Is that the behavior you're looking for?

If so, one of the things we added to Enterprise Gateway was the ability to set this [parameter to reference a wild card](https://github.com/jupyter-server/enterprise_gateway/blob/7ab3ebee4138d83cf13e6869c0236ebec5b4d9ec/enterprise_gateway/services/kernels/handlers.py#L62-L66) (e.g., `[*]`).  This instructs EG to "allow any env's specified in the kernel start request body".

In EG, `ENV_WHITELIST` is named `EG_CLIENT_ENVS`.  Seems like we could allow a similar change in JKG to keep the two gateway operations reasonably synchronized. 

If this would address your use-case, please feel free to add a PR as our support capabilities are extremely limited.
